In [17]:
brand_name = [
    "9ff",
    "ABT Sportsline",
    "AC Cars",
    "ADK",
    "AGCO",
    "AIL",
    "AITO",
    "AM General",
    "AMC",
    "AMI",
    "ARO",
    "ASA",
    "AUDI",
    "Abarth",
    "Acadian",
    "Acura",
    "Adam Motor Company",
    "Afeela",
    "Agrale",
    "Aion",
    "Aiways",
    "Aixam",
    "Ajax",
    "Alatac",
    "Albion",
    "Alesbury",
    "Alfa Romeo",
    "Allard",
    "Almac",
    "Alpha Sports",
    "Alpina",
    "Alpine",
    "Alta",
    "Alternative Cars",
    "Alvis",
    "Amati Cars",
    "Amazonas Motos Especiais",
    "Amazonas Motos Especiais (AME)",
    "American Simplex",
    "Amherst",
    "Amilcar",
    "Amphicar",
    "Amplex",
    "Anadol",
    "Anasagasti",
    "Andino",
    "Anglo-Dane",
    "Anteros",
    "Anziel",
    "Apal",
    "Arash",
    "Arcfox",
    "Arcimoto",
    "Argentina",
    "Ariel",
    "Armstrong Siddeley",
    "Arrinera",
    "Arrival",
    "Artega",
    "Ascari",
    "Ascort",
    "Ashok Leyland",
    "Asia",
    "Aspa",
    "Aspark",
    "Aspid",
    "Aston Martin",
    "Astra",
    "Asüna",
    "Atlas Honda",
    "Attica",
    "Auburn",
    "Audi",
    "Aurica",
    "Aurus Motors",
    "Austin-Healey",
    "Australian Six",
    "Australis",
    "Austro-Daimler",
    "Austro-Tatra",
    "Auto Avio Costruzioni",
    "Auto Union",
    "Auto and motor shows",
    "Auto-Mixte",
    "AutoLatina",
    "Autobianchi",
    "Autokinitoviomihania Ellados",
    "Automeccanica",
    "Automobile manufacturers",
    "Automobile sales by model",
    "Automotive design",
    "Automotive engineering",
    "Autozam",
    "Avatr Technology",
    "Avia",
    "Avibrás",
    "AzSamand",
    "BAIC Group",
    "BET",
    "BMW",
    "BMW M",
    "BYD",
    "BYD Bus",
    "Baby-Brousse",
    "Bahman",
    "Bajaj Auto",
    "Balkania",
    "Ballot",
    "Bangladesh",
    "Baojun",
    "Baolong",
    "Beattie",
    "Beaumont",
    "Beijing",
    "Beijing Automobile Works",
    "Beijing Off-road",
    "BelAZ",
    "BelGee",
    "Belarus",
    "Benelli",
    "Bentley",
    "Berkeley",
    "Berliet",
    "Bernardini",
    "Bertone",
    "Bestune",
    "Biamax",
    "Birchfield",
    "Birkin",
    "Bitter",
    "Bizzarrini",
    "Bjering",
    "Blade",
    "Bollinger Motors",
    "Bolloré",
    "Bolwell",
    "Bombardier Recreational Products",
    "Bond",
    "Borgward",
    "Borland Racing Developments",
    "Brabus",
    "Brasil & Movimento",
    "Brasinca",
    "Brazil",
    "Bremach",
    "Brems",
    "Bricklin",
    "Briggs Automotive Company (BAC)",
    "Bristol",
    "British Salmson",
    "Brock",
    "Brooks",
    "Buchanan",
    "Buckle",
    "Buckler",
    "Buddy",
    "Bufori",
    "Bugatti",
    "Buick",
    "Bulgaralpine",
    "Bulgaria",
    "Bulgarrenault",
    "Bullet",
    "Bus manufacturers",
    "Bush Ranger",
    "Busscar",
    "Byton",
    "C.AR",
    "CAMI",
    "CFMoto",
    "CMC",
    "CT&T",
    "Cadillac",
    "Caldwell Vale",
    "Callaway",
    "Campagna",
    "Canada",
    "Canadian",
    "Canadian Electric Vehicles",
    "Canadian Motor",
    "Candia",
    "Canoo",
    "Carbuss",
    "Carlton",
    "Casalini",
    "Category",
    "Caterham Cars",
    "Caterpillar Brasil",
    "Ceer Motors",
    "Chambers Motors",
    "Chamonix",
    "Chamonix Athos",
    "Chang'an Motors",
    "Changan",
    "Changan Nevo",
    "Changfeng Motor",
    "Changhe",
    "Chatenet",
    "Checker",
    "Cheetah",
    "Chenard-Walcker",
    "Chery",
    "Chery New Energy",
    "Chevrolet",
    "Chevron",
    "ChienThang",
    "China",
    "Chinkara Motors",
    "Chrysler",
    "Chrysler Europe",
    "Cisitalia",
    "Citroën",
    "CityEl",
    "Cizeta",
    "Clan",
    "Clinton",
    "Cobra",
    "Coda",
    "Colonial",
    "Colt",
    "Comarth",
    "Comil",
    "Companhia Industrial Santa Matilde",
    "Cord",
    "Countries by motor vehicle production",
    "Countries by vehicles per capita",
    "Covini",
    "Credo",
    "Croatia",
    "Crosley",
    "Crossley",
    "Crowther",
    "Csepel",
    "Csonka",
    "Cupra",
    "Custoca",
    "Czech Republic",
    "Czinger",
    "DAF",
    "DAF Trucks",
    "DB",
    "DFSK",
    "DIM",
    "DKW",
    "DOK-ING",
    "DR",
    "DS",
    "Dacia",
    "Dadi",
    "Daewoo",
    "Daewoo Automobile S.A.",
    "Dafra Motos",
    "Daihatsu",
    "Daimler",
    "Dansk",
    "Dardo",
    "Darracq",
    "Datsun",
    "David Brown",
    "Dayang",
    "De Dion-Bouton",
    "De Joux",
    "De Tomaso",
    "De Wandre",
    "De la Chapelle",
    "DeLorean Motor Company",
    "DeSoto",
    "Debadging",
    "Deepal",
    "Delage",
    "Delahaye",
    "Delecroix",
    "Dellow",
    "Dennison",
    "Denza",
    "Denzel",
    "Derways",
    "Detroit Electric",
    "Devaux",
    "Devel Motors",
    "Devon",
    "Devrim",
    "Dewan Farooque Motors",
    "Diana",
    "Diar",
    "Dina",
    "Distribuidora de Automóveis, Caminhões e Ônibus Nacionais",
    "Dodge",
    "Dominion Motors Frontenac",
    "Dongfeng",
    "Dongfeng Fengshen",
    "Dongfeng Nammi",
    "Donkervoort",
    "Drako Motors",
    "Drive time",
    "Ducati do Brasil",
    "Duesenberg",
    "Durant",
    "Dutton",
    "E-Z-GO",
    "EBIAM",
    "ELVO",
    "Eagle",
    "Edison Motors",
    "Edran",
    "Edsel",
    "Effa Motors",
    "Egypt",
    "Eicher Motors",
    "El Car",
    "Elcat",
    "Electric Raceabout",
    "Elfin Cars",
    "Elio Motors",
    "Elva",
    "Enfield",
    "Engenheiros Especializados",
    "Eniak",
    "Envoy",
    "Epic",
    "Equus Automotive",
    "ErAZ",
    "Esemka",
    "Etox",
    "Eunos",
    "Eurostar Automobilwerk",
    "Everson",
    "Everus",
    "Excelsior",
    "Exeed",
    "Exlantix",
    "Eysink",
    "F&M",
    "FAP",
    "FAW Pakistan",
    "FAW Tianjin (Xiali)",
    "FCA Srbija",
    "FNM",
    "FNM Fábrica Nacional de Motores",
    "FSO",
    "Fabral",
    "Facel Vega",
    "Facelift",
    "Fairthorpe",
    "Falcon",
    "Fangchengbao",
    "Faraday",
    "Farboud Limited",
    "Farus",
    "Fejes",
    "Felber Autoroller",
    "Fengon",
    "Ferrari",
    "Ferrari Polski",
    "Fiat",
    "Fiat Chrysler Canada",
    "Finch Restorations",
    "Firefly",
    "First Automotive Works",
    "Fisker",
    "Flaid",
    "Foday",
    "Force Motors",
    "Ford",
    "Ford Canada",
    "Ford Romania",
    "Ford Union",
    "Ford-Balt",
    "Ford-Werke",
    "Formosa",
    "Foton",
    "Fraser",
    "Frazer",
    "Frazer Nash",
    "Freightliner",
    "Frontenac",
    "GAC Group",
    "GAC Ireland",
    "GAZ",
    "GM Korea",
    "GMC",
    "GMK",
    "GMB",
    "GR",
    "GSM",
    "GTA Motor",
    "Ganja Auto Plant",
    "Gareau",
    "Gatter",
    "Geely (Jili)",
    "Geely Auto",
    "Geely Galaxy",
    "Geely Geometry",
    "Geijer",
    "Gemballa",
    "General Motors",
    "General Motors Canada",
    "Genesis",
    "Geo",
    "Gerard Farre",
    "Germain",
    "Germany",
    "Ghandhara Industries",
    "Ghandhara Nissan",
    "Giannini",
    "Gilbern",
    "Gillet",
    "Ginetta",
    "Giocattolo",
    "Giottiline",
    "Girardin Minibus",
    "Glas",
    "Glossary",
    "Gobron-Brillié",
    "Goggomobil",
    "Goliath",
    "Gonow",
    "Gordon Murray Automotive",
    "Gordon-Keeble",
    "Granu",
    "Gray-Dort",
    "Great Wall Motors",
    "Grecav",
    "GreenPower",
    "Grofri",
    "Grupo CNH Industrial",
    "Grupo Caoa",
    "Gräf & Stift",
    "Gurgel",
    "HSV",
    "HTT Automobile",
    "Hafei",
    "Haima Automobile",
    "Hansa",
    "Harley-Davidson",
    "Hartnett",
    "Haval",
    "Hawtai (Huatai)",
    "Hayden Dart",
    "Heavy Industries Taxila",
    "Heinkel",
    "Hennessey",
    "Hercules",
    "Heron",
    "Hi-Tech",
    "Hicom",
    "Hillman",
    "Hindustan Motors",
    "Hino",
    "Hino Motors",
    "Hinopak",
    "Hispano Suiza",
    "Hispano-Argentina",
    "History of the automobile",
    "History of the internal combustion engine",
    "Ineos Automotive",
    "Innocenti",
    "Innoson Vehicle Manufacturing",
    "Inokom",
    "Intermeccanica",
    "Invacar",
    "Invicta",
    "Iran",
    "Iran Khodro",
    "Ireland",
    "Iros",
    "Isdera",
    "Iso",
    "Isuzu",
    "Italdesign",
    "Italy",
    "Iveco",
    "Izh",
    "Izuogu",
    "J-Bus",
    "JAC Motors",
    "JMC",
    "JPX Indústria e Comércio",
    "Jacer",
    "Jaecoo",
    "Jaguar",
    "Jaguar e Land Rover Brasil",
    "Jawa",
    "Jeecy-Vea",
    "Jeep",
    "Jehle",
    "Jensen",
    "Jetour",
    "Jiangling",
    "Jinbei",
    "John Deere",
    "Jonway",
    "Jordan",
    "Joss Developments",
    "Jowett",
    "Juwel",
    "Jösse Car",
    "K-1 Engineering",
    "KTM",
    "Kaditcha",
    "Kaipan",
    "Kaiser",
    "KamAZ",
    "Kantanka",
    "Karenjy",
    "Karma",
    "Karmann-Ghia",
    "Karosa",
    "Kawasaki",
    "Kawasaki Motors",
    "Keating Supercars",
    "Kenworth",
    "Kenya",
    "Keraboss",
    "Khodro Kaveer",
    "Kia",
    "Kia Lucky Motors",
    "Kiira",
    "King Long",
    "Kioleides",
    "Kish Khodro",
    "Koenigsegg",
    "Komatsu",
    "Kongsberg",
    "Korres",
    "Korvensuu",
    "KrAZ",
    "Krampers",
    "Kymco",
    "LIAZ",
    "LaFayette",
    "LaSalle",
    "Lada",
    "Lafer",
    "Lagonda",
    "Lamborghini",
    "Lanchester",
    "Lancia",
    "Land Rover",
    "Landwind",
    "Laraki",
    "Lea-Francis",
    "Leapmotor",
    "Leitch",
    "Lexus",
    "Leyland",
    "Li Auto",
    "Libelle",
    "Lifan",
    "Ligier",
    "Lincoln",
    "Lion Bus",
    "Litex Motors",
    "Lloyd",
    "Lloyd-Hartnett",
    "Lobini",
    "Local",
    "Lohner–Porsche",
    "London Electric Vehicle Company",
    "London Six",
    "Lonsdale",
    "Lorraine-Dietrich",
    "Lotec",
    "Lotus",
    "Lotus-Cortina",
    "Lucid",
    "Luxeed",
    "Luxgen",
    "Lynk & Co",
    "Lyons",
    "M-Hero",
    "MAN",
    "MAVA-Renault",
    "MBM",
    "MEBEA",
    "MG",
    "MG JW Automobile",
    "MG Motor",
    "MTX / Metalex",
    "MVM",
    "MW Motors",
    "Mack",
    "Maextro",
    "Mafersa",
    "Magirus",
    "Magna Steyr",
    "Magneti Marelli",
    "Mahindra",
    "Mahindra & Mahindra Limited",
    "Malaysia",
    "Manic GT",
    "Marauder",
    "Marcopolo",
    "Marlborough",
    "Marmon",
    "Marquette",
    "Marussia",
    "Maruti",
    "Maruti Suzuki",
    "Mascarello",
    "Maserati",
    "Massey Ferguson",
    "Master",
    "Mastretta",
    "Mathis",
    "Matra",
    "Maxus",
    "Maxwell",
    "Maybach",
    "Mazda",
    "Mazzanti",
    "McLaren",
    "McLaughlin",
    "McRae",
    "Meeussen",
    "Melex",
    "Melkus",
    "Mercedes-Benz",
    "Mercer",
    "Mercury",
    "Merkur",
    "Messerschmitt",
    "Meteor",
    "Metropolitan",
    "Micro",
    "Microcar",
    "Microenterprise",
    "Midas",
    "Miesse",
    "Millat Tractors",
    "Minerva",
    "Minetti Sports Cars",
    "Minor automotive manufacturing groups",
    "Minsk Automobile Plant",
    "Mistral",
    "Mitsubishi",
    "Mitsubishi Fuso",
    "Mitsuoka",
    "Mobius",
    "Monarch",
    "Monteverdi",
    "Moon",
    "Moose Jaw Standard",
    "Morattab",
    "Morgan",
    "Morocco",
    "Morris",
    "Moskvich",
    "Moskvitch",
    "Mosler",
    "Motor vehicle",
    "Nio",
    "Nissan",
    "Nobe",
    "Noble",
    "Norsk",
    "Nota",
    "Nova Bus",
    "Novoplan",
    "Ntekop",
    "Nu Ride Inc.",
    "Nyayo",
    "O.S.C.A.",
    "ORA",
    "Oakland",
    "Obvio!",
    "Oldsmobile",
    "Oltcit",
    "Omoda",
    "Onvo",
    "Opel",
    "Optimal Energy",
    "Orca",
    "Organisation Internationale des Constructeurs d'Automobiles",
    "Oshan",
    "PGO",
    "PRB",
    "PVP Karting",
    "Packard",
    "Pagani",
    "Pak Suzuki",
    "Pakistan",
    "Pan-Car",
    "Panhard",
    "Panhard et Levassor",
    "Panoz",
    "Panther",
    "Paramount",
    "Pars Khodro",
    "Paykan",
    "Peel Engineering Company",
    "Peerless",
    "Pegaso",
    "Pellandini",
    "Perana",
    "Perodua",
    "Peterbilt",
    "Peugeot",
    "Philippines",
    "Piaggio",
    "Pieper",
    "Pindad",
    "Pininfarina",
    "Pipe",
    "Pirin-Fiat",
    "Plymouth",
    "Poland",
    "Polaris",
    "Polarsun Automobile",
    "Polestar",
    "Polski Fiat",
    "Pontiac",
    "Porsche",
    "Portaro",
    "Praga",
    "Pragoti",
    "Premier",
    "Prevost",
    "Prince",
    "Prince DFSK",
    "Princess",
    "Protea",
    "Proto",
    "Proton",
    "Puch",
    "Puma",
    "Puma Automóveis",
    "Puma Clubman",
    "Purvis Eureka",
    "Pyeonghwa Motors",
    "Python",
    "Qoros",
    "Queen",
    "Qvale",
    "RAESR",
    "RW",
    "Racefab",
    "Radical",
    "Ram Trucks",
    "Rambler",
    "Ranger",
    "Rebadging",
    "Record",
    "Redline",
    "Reliant",
    "Renault",
    "Renault Samsung",
    "Renault Trucks",
    "Rengsjöbilen",
    "Replicar Hellas",
    "Reva",
    "Revoz",
    "Rezvani",
    "Riley",
    "Rimac",
    "Rinspeed",
    "Rising Auto",
    "Rivian",
    "Roewe",
    "Rolls-Royce",
    "Romania",
    "Rosenbauer",
    "Rosengart",
    "Rossion",
    "Royal Enfield Brasil",
    "Royal Star",
    "Ruf",
    "Runner Automobiles",
    "Russia",
    "Rába",
    "SAIC Motor",
    "SAIPA",
    "SEAT",
    "SIN Cars",
    "SSC",
    "STI",
    "Saab",
    "Saehan",
    "Saenara",
    "Saker",
    "Saleen",
    "Salmson",
    "SamKochAvto",
    "Santana",
    "Sao",
    "Saturn",
    "Savage Rivale",
    "Saviem",
    "Sazgar",
    "Scania",
    "Scavas",
    "Scion",
    "Scuderia Cameron Glickenhaus",
    "Senova",
    "Serbia",
    "Seres",
    "Shaanxi Automobile Group",
    "Shahab Khodro",
    "Shaka",
    "Shamrock",
    "Shanghai Maple Guorun Automobile",
    "Shelby American",
    "Shineray do Brasil",
    "Shinjin",
    "Shrike",
    "Shuanghuan",
    "Siata",
    "Sichuan Tengzhong",
    "Simca",
    "Simca do Brasil",
    "Sisu Auto",
    "SlovBus",
    "Slovakia",
    "Smart",
    "Sofia",
    "Sollers",
    "Soueast",
    "Soueast Motors",
    "Spania GTA",
    "Spartan",
    "Spartan Motor Company",
    "Speranza",
    "Spirra",
    "Springuel",
    "Spyker",
    "Ssangyong",
    "Standard",
    "Startup",
    "Statesman",
    "Staver",
    "Stearns-Knight",
    "Steel Brothers",
    "Stelato",
    "Stelka",
    "Stellantis",
    "Steyr Motors GmbH",
    "Steyr automobile",
    "Steyr-Daimler-Puch",
    "Stohr Cars",
    "Studebaker",
    "Styl Kar",
    "Subaru",
    "Sunbeam",
    "Sunbeam-Talbot",
    "Sundown Motos",
    "Sungri Motors",
    "Superformance",
    "Suzuki",
    "Swallow",
    "Sweden",
    "TAC",
    "TAM",
    "TANK",
    "TAV",
    "TAZ",
    "TD2000",
    "THACO",
    "TMC Costin",
    "TOGG",
    "TVR",
    "TagAZ",
    "Taiwan",
    "Takeoka Auto Craft",
    "Talbot",
    "Talbot-Lago",
    "Tangalakis",
    "Tarrant",
    "Tarso Marques",
    "Tata Motors",
    "Tatra",
    "Tauro Sport Auto",
    "TechArt",
    "Techrules",
    "Tecnologia Automotiva Catarinense",
    "Temsa",
    "Tesla",
    "Thai Rung",
    "Thailand",
    "Theologou",
    "Think",
    "Thunder Power",
    "Timeline of motor vehicle brands",
    "Timmis",
    "Timor",
    "Tjorven",
    "Tofaş",
    "Tornado",
    "Toroidion",
    "Toyopet",
    "Toyota",
    "Toyota Canada",
    "Trabant",
    "Tracta",
    "Tramontana (sports car)",
    "Trekka",
    "Trident",
    "Trion Supercars",
    "Triumph",
    "Triumph Brazil",
    "Trnavské automobilové závody",
    "Trojan",
    "Troliga Bus",
    "Troll",
    "Troller",
    "Truck manufacturers",
    "Trumpchi",
    "Tudhope",
    "Turkey",
    "Turner",
    "Tushek & Spigel",
    "Tushek & Spigel Supercars",
    "Tyrrell",
    "UAZ",
    "UD Trucks",
    "Uri-Automobile",
    "Uttara",
    "UzAuto Motors",
    "VAM",
    "VDL Nedcar",
    "VELAM",
    "VLEGA Gaucho",
    "VW-Porsche",
    "Valmet Automotive",
    "Valtra",
    "Van Doorne's Automobiel Fabrieken",
    "Vanaja",
    "Vanden Plas",
    "Vauxhall",
    "Vector",
    "Vehicle Production Group",
    "Velorex",
    "Vencer",
    "Venturi",
    "Venucia",
    "Vespa",
    "Viação Itapemirim",
    "Vicinity Motor Corp.",
    "Vietnam",
    "VinFast",
    "Vinaxuki",
    "Vincke",
    "Vivinus",
    "Voisin",
    "Volkswagen",
    "Volkswagen aka VWB",
    "Volkswagen do Brasil",
    "Voltz Motors",
    "Volvo",
    "Volvo Cars",
    "Voyah",
    "W Motors",
    "Wallyscar",
    "Walter",
    "Walton Motors",
    "Wanderer",
    "Wartburg",
    "Warwick",
    "Western Star",
    "Wey",
    "Wheego",
    "Whirlpool",
    "Wiesmann",
    "Wikov",
    "Willys",
    "Wolseley",
    "Wood",
    "Wuling",
    "XPeng",
    "Xiaomi Auto",
    "Xinkai",
    "Yamaha",
    "Yamaha Motor",
    "Yamaha Motor Pakistan",
    "Yangwang",
    "Yema Auto",
    "Youngman",
    "Yue Long/Yulon/YLN",
    "Yuejin",
    "Yugo",
    "Yusheng",
    "Yutong",
    "ZENN",
    "ZX Auto",
    "Zacua",
    "Zagross Khodro",
    "Zanella",
    "Zastava",
    "Zastava TERVO",
    "Zbrojovka Brno",
    "Zeekr",
    "Zenvo Automotive",
    "Zeta",
    "ZiL",
    "Zimmer",
    "Zotye",
    "Bucciali",
    "Ducati",
    "Hispano-Suiza",
    "Richard-Brasier",
    "RUF",
    "Marmon",
    "Niclausse",
    "Laverda",
    "G.A.R",
    "Citroen",
    "Turcat-MÃ©ry",
    "Delaunay-Belleville",
    "Prunel",
    "Decauville",
    "Bedelia",
    "Sizaire-FrÃ¨res",
    "Altos Moto",
    "Honda",
    "Shelby",
]

In [18]:
import pandas as pd

In [19]:
file = "bonhams/final/bonhams_2025_upcoming.csv"
df = pd.read_csv(file)
df.head()

,Title,Title_sep,Chassis no.,VIN.,Engine no.,Price,Currency,Low Estimate,High Estimate,Sold Status,...,info_i_3,info_6,info_i_4,info_i_5,info_i_6,info_i_7,info_i_8,info_i_9,info_i_10,listing_URL
0,1998 Bentley Turbo RT Coachwork by Mulliner Ch...,1998 Bentley Turbo RT Coachwork by Mulliner,SCBZP26C0WCX66708,NaN,NaN,NaN,EUR,"80,000","120,000",Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://cars.bonhams.com/auction/30406/preview...
1,1972 Porsche 911E 2.4-Litre Targa 'Ӧlklappe' C...,1972 Porsche 911E 2.4-Litre Targa 'Ӧlklappe',9112210722,NaN,6221475,NaN,EUR,"70,000","100,000",Sold,...,"Importantly, the car still has its original en...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://cars.bonhams.com/auction/30406/preview...
2,1961 Alfa Romeo Giulietta Spider Chassis no. 1...,1961 Alfa Romeo Giulietta Spider,1495 11358,NaN,00106 00878,NaN,EUR,"60,000","80,000",Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://cars.bonhams.com/auction/30406/preview...
3,1967 Volkswagen Type 2 T1 Bus Chassis no. 2471...,1967 Volkswagen Type 2 T1 Bus,247120714,NaN,NaN,NaN,EUR,"40,000","60,000",Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://cars.bonhams.com/auction/30406/preview...
4,1972 Aston Martin V8 Chassis no. V8/10519/RCA ...,1972 Aston Martin V8,V8/10519/RCA,NaN,V/540/376,NaN,EUR,"130,000","180,000",Unsold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://cars.bonhams.com/auction/30406/preview...

In [20]:
df.columns

Index(['Title', 'Title_sep', 'Chassis no.', 'VIN.', 'Engine no.', 'Price',
       'Currency', 'Low Estimate', 'High Estimate', 'Sold Status',
       'Reserve Status', 'info_0', 'info_i_0', 'info_i_1', 'Event Date',
       'Event Location', 'info_1', 'info_2', 'info_3', 'info_4', 'info_5',
       'info_i_2', 'info_i_3', 'info_6', 'info_i_4', 'info_i_5', 'info_i_6',
       'info_i_7', 'info_i_8', 'info_i_9', 'info_i_10', 'listing_URL'],
      dtype='object')

In [21]:
null_rows_specific = df[df["Title"].isnull()]
print(null_rows_specific["listing_URL"])
file_path = "example.txt"

# Write content to the file
with open(file_path, "w") as file:
    for text in null_rows_specific["listing_URL"]:
        file.write(text + "\n")

Series([], Name: listing_URL, dtype: object)

In [22]:
data = df[df["Title"].notna() & (df["Title"] != "")]

In [23]:
sentences = data["Title_sep"]

In [24]:
sentences

0           1998 Bentley Turbo RT Coachwork by Mulliner
1          1972 Porsche 911E 2.4-Litre Targa 'Ӧlklappe'
2                      1961 Alfa Romeo Giulietta Spider
3                         1967 Volkswagen Type 2 T1 Bus
4                                  1972 Aston Martin V8
                            ...
75                          1957 BMW 503 Coupe Series 1
76    1960 Porsche 356B Super 90 Roadster Coachwork ...
77    1987 Nissan Skyline 'Type HR31' GTS-R NISMO Gr...
78    1965 Fiat 850 'Abarth 1000 OT' Spider Coachwor...
79                     1955 Jaguar XK140 'OTS' Roadster
Name: Title_sep, Length: 80, dtype: object

In [25]:
len(sentences)

80

In [26]:
import re


def find_brands_in_sentence(sentence, brand_name):
    matches = []
    for brand in brand_name:
        # Find all occurrences of the brand in the sentence
        match = re.findall(rf"\b{re.escape(brand)}\b", sentence)
        if match:
            matches.extend(match)  # Add the matched brand to the list
    return matches[0] if matches else ""

In [27]:
total = []
for sentence in sentences:
    if isinstance(sentence, str):
        # Call the function and print the result
        result = find_brands_in_sentence(sentence, brand_name)
        total.append(result)
    else:
        print(sentence)
        total.append("")

In [28]:
len(total)

80

In [29]:
data["Make"] = total

In [30]:
pattern = r"\b\d{4}\b"
final_year = []
for sentence in sentences:
    match = re.search(pattern, sentence)

    # Extracted year
    if match:
        #print(match.group(0))
        year = match.group(0)
    else:
        year = ""
    final_year.append(year)

In [31]:
len(final_year)

80

In [32]:
data["Year"] = final_year

In [33]:
test_d = data[["Title_sep", "Make"]]

In [34]:
model_final = []
for idx, (Title, Make) in enumerate(zip(test_d["Title_sep"], test_d["Make"])):
    if Make:
        pattern = rf"\b{re.escape(Make)}\b"
        parts = re.split(pattern, Title)
        model_final.append(parts[1])
    else:
        model_final.append("")

In [35]:
len(model_final)

80

In [36]:
data["Model"] = model_final

In [37]:
data.columns

Index(['Title', 'Title_sep', 'Chassis no.', 'VIN.', 'Engine no.', 'Price',
       'Currency', 'Low Estimate', 'High Estimate', 'Sold Status',
       'Reserve Status', 'info_0', 'info_i_0', 'info_i_1', 'Event Date',
       'Event Location', 'info_1', 'info_2', 'info_3', 'info_4', 'info_5',
       'info_i_2', 'info_i_3', 'info_6', 'info_i_4', 'info_i_5', 'info_i_6',
       'info_i_7', 'info_i_8', 'info_i_9', 'info_i_10', 'listing_URL', 'Make',
       'Year', 'Model'],
      dtype='object')

In [38]:
new_order = [
    "Title",
    "Year",
    "Make",
    "Model",
    "Sold Status",
    "Price",
    "Currency",
    "Low Estimate",
    "High Estimate",
    "Reserve Status",
    "Chassis no.",
    "VIN.",
    "Engine no.",
    "info_0",
    "info_1",
    "info_2",
    "info_3",
    "info_4",
    "info_5",
    "info_6",
    # "info_7",
    # "info_8",
    # "info_9",
    # "info_10",
    "info_i_0",
    "info_i_1",
    "info_i_2",
    "info_i_3",
    "info_i_4",
    "info_i_5",
    "info_i_6",
    "info_i_7",
    "info_i_8",
    "info_i_9",
    "info_i_10",
    # "info_i_11",
    # "info_i_12",
    # "info_i_13",
    # "info_i_14",
    # "info_i_15",
    # "info_i_16",
    # "info_i_17",
    "Event Date",
    "Event Location",
    "listing_URL",
]

In [39]:
data_new_order = data[new_order]

In [40]:
data_new_order.to_csv(
    "bonhams/final_clean/bonhams_2025_final_clean_upcoming.csv", index=False
)

In [2]:
import pandas as pd

In [46]:
file = "bonhams/final_clean/bonhams_2024_final_clean.csv"
df = pd.read_csv(file)
#df.head()

In [47]:
df.columns

Index(['Title', 'Year', 'Make', 'Model', 'Sold Status', 'Price', 'Currency',
       'Low Estimate', 'High Estimate', 'Reserve Status', 'Chassis no.',
       'VIN.', 'Engine no.', 'info_0', 'info_1', 'info_2', 'info_3', 'info_4',
       'info_5', 'info_6', 'info_7', 'info_8', 'info_9', 'info_10', 'info_11',
       'info_12', 'info_13', 'info_14', 'info_15', 'info_16', 'info_17',
       'info_i_0', 'info_i_1', 'info_i_2', 'info_i_3', 'info_i_4', 'info_i_5',
       'info_i_6', 'info_i_7', 'info_i_8', 'info_i_9', 'info_i_10',
       'info_i_11', 'info_i_12', 'info_i_13', 'info_i_14', 'info_i_15',
       'info_i_16', 'info_i_17', 'info_i_18', 'info_i_19', 'info_i_20',
       'info_i_21', 'info_i_22', 'info_i_23', 'info_i_24', 'info_i_25',
       'Event Date', 'Event Location', 'listing_URL'],
      dtype='object')

In [48]:
# Replace empty strings with corresponding values from the "Last Name" column
df["Chassis no."] = df["Chassis no."].replace("", None)  # Convert empty strings to NaN
df["Chassis no."] = df["Chassis no."].combine_first(
    df["VIN."]
)  # Fill NaN with "Last Name"

In [49]:
df = df.drop(columns=["VIN."])

In [50]:
df.to_csv(
    "bonhams/final_clean_merge/bonhams_2024_final_clean_merge_date.csv", index=False
)

In [1]:
import pandas as pd

In [126]:
df = pd.read_csv("bonhams/final_clean_merge/bonhams_2024_final_clean_merge_date.csv")

In [154]:
null_rows_specific = df[df["Event Location"].isnull()]
urls = null_rows_specific["listing_URL"]

In [155]:
len(urls)

0

In [156]:
urls

Series([], Name: listing_URL, dtype: object)

In [157]:
for url in urls:
    if url.split("/")[4] == "29264":
        df.loc[df["listing_URL"] == url, "Event Location"] = (
            "Newport, Rhode Island, International Tennis Hall of Fame"
        )

In [158]:
write_filename = f"bonhams/final_clean_done/bonhams_2024_final_clean_merge_date.csv_done.csv"
df.to_csv(write_filename, index=False)

In [194]:
file = "bonhams/final_clean_done/bonhams_2023_final_clean_merge_date.csv_done.csv"
df = pd.read_csv(file)

In [195]:
df["Chassis no."] = (
    df["Chassis no."].str.replace(r"Coachwork.*", "", regex=True).str.strip()
)

In [196]:
df["Chassis no."] = (
    df["Chassis no."].str.replace(r"Design.*", "", regex=True).str.strip()
)

In [197]:
df["Chassis no."] = df["Chassis no."].str.split("Engine no.").str[0].str.strip()

In [198]:
write_filename = (
    f"bonhams/final_clean_done_new/bonhams_2023_final_clean_done.csv"
)
df.to_csv(write_filename, index=False)

In [8]:
for i in range(29,30):
    print(i)

29